<a href="https://colab.research.google.com/github/HamidSyed298/PyTorch-for-Deep-Learning-Machine-Learning/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)
Read it

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch
import numpy as np
X = torch.rand(7,7)
X
# Create random tensor


tensor([[0.8986, 0.2899, 0.2232, 0.0685, 0.2350, 0.3422, 0.9976],
        [0.1572, 0.9577, 0.7177, 0.9924, 0.3183, 0.0123, 0.0378],
        [0.4438, 0.9030, 0.5789, 0.5398, 0.3169, 0.3580, 0.6147],
        [0.5059, 0.6164, 0.6208, 0.7780, 0.6121, 0.2387, 0.3436],
        [0.8695, 0.8900, 0.9010, 0.3648, 0.9699, 0.5619, 0.6206],
        [0.5811, 0.4056, 0.1034, 0.2657, 0.3805, 0.4849, 0.0744],
        [0.1533, 0.0724, 0.6479, 0.0241, 0.5856, 0.5244, 0.7312]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
Y = torch.rand(1,7)
Z = torch.matmul(X,Y.T)
# Perform matrix multiplication 


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
RANDOM_SEED = torch.manual_seed(0)

# Create two random tensors
X = torch.rand(7,7)
#RANDOM_SEED = torch.manual_seed(0)
#If the above line is uncommented, then the answer is different as Random Seed gets applied to both of the tensors then
Y = torch.rand(1,7)

# Matrix multiply tensors
Z = torch.matmul(X,Y.T)
Z

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [20]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device{device}")
# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
print(tensor_A,tensor_B)

Devicecuda
tensor([[0.8579, 0.4486, 0.5139],
        [0.4569, 0.6012, 0.8179]], device='cuda:0') tensor([[0.9736, 0.8175, 0.9747],
        [0.4638, 0.0508, 0.2630]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [24]:
# Perform matmul on tensor_A and tensor_B
C = torch.matmul(tensor_A,tensor_B.T)
C, C.shape

(tensor([[1.7029, 0.5559],
         [1.7335, 0.4576]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [25]:
# Find max
max_C = torch.max(C)
print(f"Maximum of C{max_C}")
# Find min
min_C = torch.min(C)
print(f"Minimum of C{min_C}")

Maximum of C1.733536958694458
Minimum of C0.4575575292110443


### 9. Find the maximum and minimum index values of the output of 7.

In [26]:
# Find arg max
max_index_C = torch.argmax(C)
print(f"Maximum value of C at index {max_index_C}")
# Find arg min
min_index_C = torch.argmin(C)
print(f"Minimum value of C at index {min_index_C}")

Maximum value of C at index 2
Minimum value of C at index 3



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
# Set seed
RANDOM_SEED = torch.manual_seed(7)

# Create random tensor
D_Tensor = torch.rand(1,1,1,10)

# Remove single dimensions
E_Tensor = D_Tensor.squeeze()


# Print out tensors and their shapes
print(f"Tensor D: {D_Tensor} and it's shape is {D_Tensor.shape}")
print(f"Tensor E: {E_Tensor} and it's shape is {E_Tensor.shape}")

Tensor D: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) and it's shape is torch.Size([1, 1, 1, 10])
Tensor E: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) and it's shape is torch.Size([10])
